# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serverx_to_server_y.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19serverx_to_server_y.proto\x12\x07serverx\" \n\rPingABRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"!\n\x0ePingABResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2R\n\x0eServerYService\x12@\n\x0bProcessPing\x12\x16.serverx.PingABRequest\x1a\x17.serverx.PingABResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'serverx_to_server_y_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PINGABREQUEST']._serialized_start=38
  _globals['_PINGABREQUEST']._serialized_end=70
  _globals['_PINGABRESPONSE']._serialized_start=72
  _globals['_PINGABRESPONSE']._serialized_end=105
  _globals['_SERVERYSERVICE']._serialized_start=107
  _globals['_SERVERYSERVICE']._serialized_end=189
# @@protoc_insertion_point(module_scope)
