# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import serverx_to_server_y_pb2 as serverx__to__server__y__pb2


class ServerYServiceStub(object):
    """Service to interact with serverY
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessPing = channel.unary_unary(
                '/serverx.ServerYService/ProcessPing',
                request_serializer=serverx__to__server__y__pb2.PingABRequest.SerializeToString,
                response_deserializer=serverx__to__server__y__pb2.PingABResponse.FromString,
                )


class ServerYServiceServicer(object):
    """Service to interact with serverY
    """

    def ProcessPing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServerYServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessPing': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessPing,
                    request_deserializer=serverx__to__server__y__pb2.PingABRequest.FromString,
                    response_serializer=serverx__to__server__y__pb2.PingABResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'serverx.ServerYService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ServerYService(object):
    """Service to interact with serverY
    """

    @staticmethod
    def ProcessPing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serverx.ServerYService/ProcessPing',
            serverx__to__server__y__pb2.PingABRequest.SerializeToString,
            serverx__to__server__y__pb2.PingABResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
